apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fs-gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fs-gateway.name" . }}
    helm.sh/chart: {{ include "fs-gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application-prod.yml: |-
    spring:
      cloud:
        gateway:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
          globalcors:
            corsConfigurations:
              "[/**]":
                allowedOrigins:
                  - '*'
                allowedMethods:
                  - OPTIONS
                  - GET
                  - POST
                allowedHeaders:
                  - '*'
          routes:
            - id: FonepayTransactionBooking
              uri: 'http://ibft-account-verification-v2:8080'
              predicates:
                - Path=/fonepaySwitch/banksconnect/transactionBooking/**

            - id: FonepaySwitchNew
              uri: 'http://ibft-account-verification-v2:8080'
              predicates:
                - Path=/v2/**
                
            - id: FonepayOAuth2IbftAuth
              uri: http://oauth2.fonepay-switch:8080
              predicates:
                - Path=/ibft/fonepayAuth/**
              filters:
                -  RewritePath=/ibft/(?<segment>.*), /$\{segment}

            - id: FonepayOAuth2ClientAuth
              uri: http://oauth2.fonepay-switch:8080
              predicates:
                - Path=/client/fonepayAuth/**
              filters:
                -  RewritePath=/client/(?<segment>.*), /$\{segment}

            - id: FonepayOAuth2Auth
              uri: http://oauth2.fonepay-switch:8080
              predicates:
                - Path=/fonepayAuth/**
              filters:
                - AddRequestHeader=Authorization, Basic VVNFUl9BRE1JTl9BUFA6cGFzc3dvcmQ=
                - AddRequestHeader=oauth-client-type, FONEPAY_USER

            - id: FonepaySwitchIso
              uri: 'http://fonepay-ibft-switch:8080'
              predicates:
                - Path=/fonepaySwitch/**

            - id: FonepaySwitchAdmin
              uri: 'http://fonepay-switch-admin-backend:8080'
              predicates:
                - Path=/fonepayAdmin/**
                 
      application:
        name: Gateway-Fonepay
    management:
      endpoint:
        health:
          show-details: always
    logging:
      level:
        root: INFO




 