replicaCount: 1
image:
  repository: nginx
  tag: stable-perl
  pullPolicy: Always
  pullSecret: repo-new
resources:
  # limits:
  # # cpu: 200m
  #  memory: 1200Mi
  requests:
   cpu: 100m
   memory: 400Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 1000
  targetMemoryUtilizationPercentage: 400
service:
  enabled: true
  type: ClusterIP
  internalPort: 8080
  externalPort: 9090
containerPorts:
  - name: http-8080
    containerPort: 8080
    protocol: TCP
  - name: management
    containerPort: 9999
    protocol: TCP
# ingress:
#   enabled: false
# pvc: 
#   enabled: false
# # persistentVolume:
# #   storage: 10Gi
# #   storageClass: standard
SERVICE_NAME: fs-switch
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  create: true
nameOverride: "fs-switch"
fullnameOverride: "fs-switch"
#Change from here
ingress:
  enabled: false
env:
  - name: management.server.port
    value: '9999'
  - name: spring.profiles.active
    value: prod
  - name: server.port
    value: '8080'
pvc:
  enabled: true
  definitions:
    fonepayswitch-deploy:
      volumeName: volume-fonepayswitch-deploy
      mountPath: /app/config/deploy
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
    fonepayswitch-cfg:
      volumeName: volume-fonepayswitch-cfg
      mountPath: /app/config/cfg
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
    fonepayswitch-log-ibft:
      volumeName: volume-fonepayswitch-log-ibft
      mountPath: /app/config/log
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
configmap:
  enabled: true
  definitions:
    fonepay-ibft-switch-config:
      name: fonepay-ibft-switch-config
      mountPath: /app/config/application-prod.properties
      subPath: application-prod.properties
      data:
        application-prod.properties: |
          spring.datasource.url=test
          spring.datasource.username=fp__switch
          spring.datasource.password=test


hostAlias:
  ip: 10.12.21.22
  hostnames:
    - abc.com
