replicaCount: 1
image:
  repository: nginx
  tag: stable-perl
  pullPolicy: Always
  pullSecret: repo-new
resources:
  # limits:
  # # cpu: 200m
  #  memory: 1200Mi
  requests:
   cpu: 100m
   memory: 480Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 1000
  targetMemoryUtilizationPercentage: 400
service:
  enabled: true
  type: ClusterIP
  internalPort: 8080
  externalPort: 9090
containerPorts:
  - name: http-8080
    containerPort: 8080
    protocol: TCP
  - name: management
    containerPort: 9999
    protocol: TCP
# ingress:
#   enabled: false
# pvc: 
#   enabled: false
# # persistentVolume:
# #   storage: 10Gi
# #   storageClass: standard
SERVICE_NAME: fs-test2
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  create: true
nameOverride: "fs-test2"
fullnameOverride: "fs-test2"
#Change from here
ingress:
  enabled: false
env:
  - name: management.server.port
    value: '9999'
  - name: spring.profiles.active
    value: prod
  - name: server.port
    value: '8080'
pvc:
  enabled: false
  definitions:
    fs-deploy:
      volumeName: volume-fs-deploy
      mountPath: /app/config/deploy
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
    fs-cfg:
      volumeName: volume-fs-cfg
      mountPath: /app/config/cfg
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
    fs-log-ibft:
      volumeName: volume-fs-log-ibft
      mountPath: /app/config/log
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
configmap:
  enabled: true
  definitions:
    gateway-config:
      name: gateway-config
      mountPath: /app/config/application-prod.yml
      subPath: application-prod.yml
      data:
        application-prod.yml: |
          spring:
            cloud:
              gateway:
                default-filters:
                  - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

hostAlias:
  ip: 10.12.21.22
  hostnames:
    - abc.com
