replicaCount: 1
image:
  repository: nginx
  tag: stable-perl
  pullPolicy: Always
  pullSecret: repo-new
resources:
  # limits:
  # # cpu: 200m
  #  memory: 1200Mi
  requests:
   cpu: 100m
   memory: 400Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 1000
  targetMemoryUtilizationPercentage: 400
service:
  enabled: true
  type: ClusterIP
  internalPort: 8080
  externalPort: 9999
# ingress:
#   enabled: false
# pvc: 
#   enabled: false
# # persistentVolume:
# #   storage: 10Gi
# #   storageClass: standard
SERVICE_NAME: fs-gateway
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  create: true
nameOverride: "test-2"
fullnameOverride: "test-2"
#Change from here
ingress:
  enabled: false
env:
  - name: management.server.port
    value: '9999'
  - name: spring.profiles.active
    value: prod
  - name: server.port
    value: '8080'
pvc:
  enabled: true
  definitions:
    fonepayswitch-deploy-2:
      volumeName: volume-fonepayswitch-deploy-2
      mountPath: /app/config/deploy
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
    fonepayswitch-cfg-2:
      volumeName: volume-fonepayswitch-cfg-2
      mountPath: /app/config/cfg
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
    fonepayswitch-log-ibft-2:
      volumeName: volume-fonepayswitch-log-ibft-2
      mountPath: /app/config/log
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
configmap:
  enabled: true
  definitions:
    fonepay-ibft-switch-config-2:
      name: fonepay-ibft-switch-config-2
      mountPath: /app/config/application-prod.properties
      subPath: application-prod.properties
      data:
        application-prod.properties: |
          spring:
            cloud:
              gateway:
                default-filters:
                  - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

hostAlias:
  ip: 10.12.21.22
  hostnames:
    - qa-aa-data-provider.fonepay.com
