image:
  repository: harbor.fonepay.com/fonepaylive/fonepay-gateway
  tag: 6
  pullPolicy: Always
  pullSecret: repo-new

replicaCount: 1
resources:
  # limits:
  # # cpu: 200m
  #  memory: 1200Mi
  requests:
   cpu: 100m
   memory: 400Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 1000
  targetMemoryUtilizationPercentage: 400
service:
  enabled: true
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: management
      port: 9999
      targetPort: 9999
      protocol: TCP
persistentVolume:
  storage: 10Gi
  storageClass: standard
SERVICE_NAME: fs-gateway
ports:
  - name: http-8080
    containerPort: 8080
    protocol: TCP
  - name: management
    containerPort: 9999
    protocol: TCP
env:
  - name: management.server.port
    value: '9999'
  - name: spring.profiles.active
    value: prod
  - name: server.port
    value: '8080'
hostAlias:
  ip: 10.12.21.22
  hostnames:
    - qa-aa-data-provider.fonepay.com

pvc:
  enabled: true
  definitions:
    fonepayswitch-deploy:
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
    fonepayswitch-cfg:
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
    fonepayswitch-log-ibft:
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 5Gi
volumes:
  - name: volume-fonepayswitch-deploy
    persistentVolumeClaim:
      claimName: fonepayswitch-deploy
  - name: volume-fonepayswitch-cfg
    persistentVolumeClaim:
      claimName: fonepayswitch-cfg
  - name: volume-fonepayswitch-log-ibft
    persistentVolumeClaim:
      claimName: fonepayswitch-log-ibft
  - name: volume-fonepay-ibft-switch
    configMap:
      name: fonepay-ibft-switch-config

volumeMounts:
  - name: volume-fonepayswitch-deploy
    mountPath: /app/config/deploy
  - name: volume-fonepayswitch-cfg
    mountPath: /app/config/cfg
  - name: volume-fonepayswitch-log-ibft
    mountPath: /app/config/log
  - name: volume-fonepay-ibft-switch
    mountPath: /app/config/application-prod.properties
    subPath: application-prod.properties

