replicaCount: 1
image:
  repository: nginx
  tag: stable-perl
  pullPolicy: Always
  pullSecret: repo-new
resources:
  # limits:
  # # cpu: 200m
  #  memory: 1200Mi
  requests:
   cpu: 100m
   memory: 400Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 1000
  targetMemoryUtilizationPercentage: 400
service:
  enabled: true
  type: ClusterIP
  internalPort: 8080
  externalPort: 9999
# ingress:
#   enabled: false
# pvc: 
#   enabled: false
# # persistentVolume:
# #   storage: 10Gi
# #   storageClass: standard
SERVICE_NAME: fs-gateway
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  create: true
nameOverride: "test"
fullnameOverride: "test"
#Change from here
ingress:
  enabled: false
env:
  - name: management.server.port
    value: '9999'
  - name: spring.profiles.active
    value: prod
  - name: server.port
    value: '8080'
configmap:
  enabled: false
  definitions:
    - name: fonepay-ibft-switch
      configMapName: fonepay-ibft-switch-config
      mountPath: /app/config/application-prod.properties
      subPath: application-prod.properties
pvc:
  enabled: true
  provisioner: "rancher.io/local-path"
  definitions:
    - name: volume-fonepayswitch-deploy
      claimName: fonepayswitch-deploy
      mountPath: /app/config/deploy
    - name: volume-fonepayswitch-cfg
      claimName: fonepayswitch-cfg
      mountPath: /app/config/cfg
    - name: volume-fonepayswitch-log-ibft
      claimName: fonepayswitch-log-ibft
      mountPath: /app/config/log
    - name: volume-fonepay-ibft-switch
      configMapName: fonepay-ibft-switch-config
      mountPath: /app/config/application-prod.properties
      subPath: application-prod.properties
hostAlias:
  ip: 10.12.21.22
  hostnames:
    - qa-aa-data-provider.fonepay.com
