apiVersion: v1
kind: Service
metadata:
  name: {{ include "fs-gateway.fullname" . }}
  labels:
    {{- include "fs-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "fs-gateway.selectorLabels" . | nindent 4 }}
