apiVersion: v1
kind: Service
metadata:
  name: {{ include "fs-gateway.fullname" . }}
  labels:
    {{- include "fs-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "fs-gateway.selectorLabels" . | nindent 4 }}
