apiVersion: v1
kind: Service
metadata:
  name: {{ include "fonepay-ibft-switch.fullname" . }}
  labels:
    {{- include "fonepay-ibft-switch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "fonepay-ibft-switch.selectorLabels" . | nindent 4 }}
